[package]
name = "kee-overlay"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
egui = "0.24.1"
egui_overlay = "0.6.0"
egui_render_wgpu = "0.6.0"
egui_window_glfw_passthrough = "0.6.0"